<?php
/**
 * Оформление заказа по шагам.
 * В зависимости от текущего шага выбирает нужный шаблон для дальнейшего вывода.
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 */

$purchase = $this->macros('emarket', 'purchase');
?>

<section class="cart">
    <div class="cart__wrapper wrapper">
        <h1><?= $this->escape($variables['header']) ?></h1>
		<?= $this->render($purchase['purchasing']['steps'], 'emarket/steps') ?>
		<?= $this->render($purchase, $this->getPurchaseTemplate($purchase)) ?>
    </div>
</section>
