<?php
/**
 * АКЦИЯ.
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 * @var iUmiHierarchyElement $newsItem
 */    
$hierarchy = umiHierarchy::getInstance();
$some_naws = $this->macros('news', 'lastlist', array('akcii', null, null, true));
$info_from_naws = $some_naws['items'];
?>

<?php 
foreach($info_from_naws as $value):
    $page = $hierarchy->getElement($value['id']);
    $anons_pic = $page->getValue('anons_pic');
?>
<li class="action__item">
	<a href="<?=$value['link']?>" class="action__image">
		<picture>
			<!--<source type="image/webp" srcset="">-->
			<img src="<?=$anons_pic?>" alt="" / >
		</picture>
	</a>
	<div class="action__content">
		<a href="<?=$value['link']?>" class="action__name"><?=$value['name']?></a>
	</div>
</li>
<?php endforeach;?>