<?php
/**
 * Контент новости.
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 * @var iUmiHierarchyElement $newsItem
 */

$newsItem = $variables['page'];
?>


<div class="free_text" umi:element-id="<?= $variables['pageId'] ?>" umi:field-name="content"
	 umi:empty="<?= $this->translate('empty_page_content') ?>">
	<?= $newsItem->getValue('content') ?>
</div>
<?= $this->render($variables, 'library/social_count') ?>
<?= $this->render($newsItem, 'news/item/date') ?>
<?= $this->render($newsItem, 'news/item/photo') ?>
