<?php
/**
 * Категория каталога товаров.
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 */
 
$level = count($variables['parents'])+1;
$variables['pageId'] = 228;
$catalog = $this->getChildCategories($variables);
$childCategoryList = $catalog['items'];
?>


<?php if($level == 1):?>
<!-- Меню -->
<section class="nav-menu">
<div class="nav-menu__wrapper wrapper">
    <nav class="nav-menu__nav-box">
        <ul class="nav-menu__list">
            <li class="nav-manu__item">
				<a href="<?= $this->getCommonVar('mydomain')?>/shop/">
					<span class="nav-menu__icon">
			  			<svg width="35" height="29">
	            <use xlink:href="img/sprite.svg#dish"></use>
	                  </svg>
					</span>
                      <span class="nav-manu__name">Все блюда</span>
				</a>
            </li>
            <?php foreach($childCategoryList as $values) :
                            if($values->id != 328):
            ?>
			<li class="nav-manu__item">
				<a href="<?= $this->getCommonVar('mydomain')?><?= $values->link?>">
					<span class="nav-menu__icon">
						<svg width="35" height="29">
	                       <use xlink:href="<?= $this->getCommonVar('mydomain')?><?= $this->getCommonVar('temp')?>img/sprite.svg#<?= $values->getValue('id_svg');?>"></use>
                        </svg>
					</span>
                    <span class="nav-manu__name"><?= $values->getName();?></span>
                </a>
			</li>
            <?php 
            endif;
            endforeach;?>
        </ul>
    </nav>
</div>
</section>
<?php endif;?>
<!-- Популярные блюда -->
<section class="goods">
	
<?php if($level == 1):?>
    <?= $this->render($variables, 'catalog/category/level1')?>
<?php else:?>
    <?= $this->render($variables, 'menu/catmenu') ?>
    <?= $this->render($variables, 'catalog/category/level2')?>
<?php endif;?>



</section>
<!-- /Популярные блюда -->