<?php
/**
 * Страница формы обратной связи.
 * Страница "Контакты" выводится по особому шаблону `webforms/page/contacts`.
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 */

$page = $variables['page'];
?>


<?php if ($this->isContactsPage($page)): ?>
	<?= $this->render($variables, 'webforms/page/contacts') ?>
<?php else: ?>
	<?= $this->render($variables, 'webforms/page/default') ?>
<?php endif; ?>
