<?php
/**
 * Карточка товара.
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 */
 
$page = $variables['page'];
$objects = $this->macros('catalog', 'getSmartCatalog', array(null, $page->getId(), 25, null, 2));
?>
<div class="goods__wrapper wrapper">
	<h2 class="goods__title title"><?= $page->getName();?></h2>
	<ul class="goods__list">
		<!-- Товар 1 -->
      <?php foreach($objects['lines'] as $value):?>
      	  <?= $this->render($value['id'], 'catalog/product/preview/index')?>
      <?php endforeach;?>
		<!-- /Товар 1 -->
	</ul>
</div>